name: first workflows

on: [push]
jobs:
  first-workflows:
    name: first step
    runs-on: ubuntu-latest # macos বদলে ubuntu-latest দিন
    steps:
      - name: Say hello
        run: |
          echo "hello world"
          echo "hello again"