name: manual workflows

on:
  workflow_dispatch:
jobs:
  first-workflows:
    name: manual step
    runs-on: ubuntu-latest 
    steps:
      - name: Say hello
        run: |
          echo "hello world"
          echo "hello again"